### ISSUE TITLE
Window may not fit the screen

### ISSUE THREAD

**Issue by edo0** [NatLee/Batch-crop-images#1]
Thank you very much for this piece of software.
Unfortunately, there seem to be no way to make wide pictures fit the computer screen, and therefore it's impossible to crop them to a wider margin - nor the minus magnifying lens will allow to make it appear smaller than 1:1.
I would be very grateful if you could look into it, if any solution could be possible
![screenshot_xl](https://user-images.githubusercontent.com/16632292/122255448-68b1ce00-cece-11eb-9188-197c9c8c4b9a.png)

**Comment by NatLee** [comment]
Thank you for this issue! :)
Did you mean your picture larger than the monitor's resolution?

**Comment by edo0** [comment]
Thank you for your reply!!
The picture I am trying to crop is a screenshot I previously took on the same computer, so the resolution coincides with that of the monitor.

To my surprise, even trying to drag it in the centre (alt + click + drag on my system, Arch), it would still behave as if displayed larger than 1920*1080 (its original size)

**Comment by edo0** [comment]
This is the original input picture
![mpv-shot0001-1](https://user-images.githubusercontent.com/16632292/122281483-999ffc00-ceea-11eb-8dc7-78ed0ef40767.png)
And this is what it looks like, when I run the program and try to center it in order to cut out the whole blue slide
![bug2-1](https://user-images.githubusercontent.com/16632292/122281624-be946f00-ceea-11eb-8da0-7f3f430aa025.png)

It seems as if it was rendered not to 100% the original size, but even more than that

**Comment by edo0** [comment]
I hope I was clear, but please do let me know, for English is not my mothertongue!

**Comment by NatLee** [comment]
Thank you for the example!
My thought is the resolution of images is out of your monitor with full screen like this
![image](https://user-images.githubusercontent.com/10178964/122299215-4781c980-cf30-11eb-87f1-670c9319265d.png)

I think the program need to resize the image before cropping.

**Comment by edo0** [comment]
Yes, it _looks as if_ the picture were wider than the monitor.
However, that should not be the case (please see the screenshot below), so I wondered if the Batch-crop-software (willingly or unwillingly) scales up the picture in the preview for cropping

![bug3](https://user-images.githubusercontent.com/16632292/122346480-49a45200-cf49-11eb-821a-49896aca3b3d.png)

**Comment by NatLee** [comment]
Okay, I'll add this as soon as possible

**Comment by NatLee** [comment]
Alright, I have added a method for scaling your preview image when it is larger than 80% of your resolution with your screen.
Take a look.

**Comment by edo0** [comment]
Thank you so much, that solved it perfectly! I am really grateful to you!!
For reference for other people who will find this super neat piece of software, I would add also the new `tk`/`tkinter` to the list of requirements.
Thank you again!

**Comment by NatLee** [comment]
Nice issue, you're welcome. 
I think `tkinter` is in python official library, so we don't need to add it in requirements.

**Comment by edo0** [comment]
Got it! That must have been specific to my Linux distribution :)
(In Arch Linux, I had to install https://archlinux.org/packages/extra/x86_64/tk/)

**Comment by shinysocks** [comment]
how do I get an image to fit in the screen if it has a greater resolution? I can't figure it out... Also cool software thanks for making this

**Comment by NatLee** [comment]
Hi @shinysocks !
Is the meaning that when you process an image but the resolution is higher than the monitor you are using?

**Comment by shinysocks** [comment]
yeah.. is there a way I can get it to fit within the window?

**Comment by NatLee** [comment]
@shinysocks Hi

Sorry, it took a long time to give a response.

In the code, I do the check for the size of monitor.

https://github.com/NatLee/Batch-crop-images/blob/42a140e64050bc71a4e1d3794de4308e40470c0f/utils/cropper.py#L20

But as you say, it seems that there is a problem.

Could I know that what's the size of your screen & your images?

**Comment by shinysocks** [comment]
i don't remember what images I used but my screen resolution in 1080p. The images were larger than that resolution

**Comment by NatLee** [comment]
@shinysocks Hi

I make a check of †he scale between monitor resolution and the size of image.

https://github.com/NatLee/Batch-crop-images/blob/7c715968157e4debdda904a71a7738fff9dba0a1/utils/cropper.py#L18

You can test it in the latest version. Thanks :)
