### ISSUE TITLE
Error on Arch when running the programme

### ISSUE THREAD

**Issue by edo0** [NatLee/Batch-crop-images#2]
Hi! 
I would like to report this error message popping up when I try to run the software
`opencv` version is 4.5.3-4
and
`python-opencv` is 4.5.3-4
```
$ python main.py
Start (x, y) = (1008, 6)
End (x, y) = (692, 257)
Traceback (most recent call last):
  File "/home/user/Pictures/Batch-crop-images-master/main.py", line 54, in <module>
    cv2.imwrite((opt.output_path / img_path.name).absolute().as_posix(), cropped_img)
cv2.error: OpenCV(4.5.3) /build/opencv/src/opencv-4.5.3/modules/imgcodecs/src/loadsave.cpp:803: error: (-215:Assertion failed) !_img.empty() in function 'imwrite'
```
Thank you for your time!

**Comment by NatLee** [comment]
Hi edo,
I think there are something wrong with the size of image.
Is there a great deal of difference with the size of your batch cropped images?

**Comment by NatLee** [comment]
@edo0 , could you give me some information of your data? Thanks!

**Comment by edo0** [comment]
Hi NatLee!! 
I am very sorry for going MIA for such a long time. My hard drive went caput and had to get onto a new one. I ended up losing some of the not-yet-backed up work, and afterwards did not manage to reproduce the error.
So far everything works perfectly, so I will close this bug

**Comment by NatLee** [comment]
Hi edo, that's alright.
If you find any errors in the future, please let me know.
Thanks! :)
